
export const INICIAR_SESION = "INICIAR_SESION";
export const REGISTRARSE = "REGISTRARSE";
export const OBTENER_USUARIO_ACTUAL = "OBTENER_USUARIO_ACTUAL";
export const RECUPERAR_CONTRASENIA = "RECUPERAR_CONTRASENIA";
