export const FETCH_CUENTAS_FROM_CLIENTE_CEDULA =
  "FETCH_CUENTAS_FROM_CLIENTE_CEDULA";
export const FETCH_TIPO_TRANSACCION = "FETCH_TIPO_TRANSACCION";
export const FETCH_TRANSACCION_BY_ID = "FETCH_TRANSACCION_BY_ID";

export const FETCH_CUENTAS_FROM_CLIENTE_ID = "FETCH_CUENTAS_FROM_CLIENTE_ID";
export const FETCH_TRANSACCIONES_CUENTA = "FETCH_TRANSACCIONES_CUENTA";
export const FETCH_CUENTA_BY_ID = "FETCH_CUENTA_BY_ID";
export const DEPOSITAR_FONDOS = "DEPOSITAR_FONDOS";
export const RETIRAR_FONDOS = "RETIRAR_FONDOS";
export const FETCH_CUENTAS_BY_CIENTE_ID = "FETCH_CUENTAS_BY_CIENTE_ID";
