export const FETCH_CUENTAS_FROM_CLIENTE_CEDULA =
  "FETCH_CUENTAS_FROM_CLIENTE_CEDULA";
export const FETCH_TIPO_TRANSACCION = "FETCH_TIPO_TRANSACCION";
export const FETCH_TRANSACCION_BY_ID = "FETCH_TRANSACCION_BY_ID";
export const FETCH_CUENTAS_FROM_CLIENTE_ID = "FETCH_CUENTAS_FROM_CLIENTE_ID";
export const FETCH_TRANSACCIONES_CUENTA = "FETCH_TRANSACCIONES_CUENTA";
export const FETCH_CUENTA_BY_ID = "FETCH_CUENTA_BY_ID";
export const FETCH_CUENTAS_BY_CIENTE_ID = "FETCH_CUENTAS_BY_CIENTE_ID";
export const FETCH_CUENTA_FROM_TERCERO = "FETCH_CUENTA_FROM_TERCERO";
export const FETCH_BENEFICIARIOS_FROM_CUENTA =
  "FETCH_BENEFICIARIOS_FROM_CUENTA";

export const DEPOSITAR_FONDOS = "DEPOSITAR_FONDOS";
export const RETIRAR_FONDOS = "RETIRAR_FONDOS";
export const TRANSFERENCIA_PERSONAL = "TRANSFERENCIA_PERSONAL";
export const TRANSFERENCIA_A_TERCERO = "TRANSFERENCIA_A_TERCERO";
export const TRANSFERENCIA_INTERBANCARIA = "TRANSFERENCIA_INTERBANCARIA";
export const CREATE_BENEFICIARIO = "CREATE_BENEFICIARIO";
export const DELETE_BENEFICIARIO = "DELETE_BENEFICIARIO";
